# Generated by Django 5.2 on 2025-05-25 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('bank_transfer', 'Bank Transfer'), ('revolut', 'Revolut'), ('wise', 'Wise'), ('paypal', 'PayPal'), ('other', 'Other')], max_length=20, null=True),
        ),
    ]
