# Generated by Django 5.2 on 2025-05-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, help_text='Enter the payment method you used (e.g. Revolut, Bank Transfer)', max_length=100, null=True),
        ),
    ]
