# Generated by Django 5.2 on 2025-05-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='user_notes',
            field=models.TextField(blank=True, help_text='Any additional notes or comments about this payment'),
        ),
    ]
