# Generated by Django 5.2 on 2025-05-25 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_alter_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedPayment',
            fields=[
            ],
            options={
                'verbose_name': 'Archived Payment',
                'verbose_name_plural': 'Archived Payments',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('payments.payment',),
        ),
    ]
