# Generated by Django 5.2 on 2025-06-01 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colivers', '0009_alter_coliver_created_at'),
        ('payments', '0008_archivedpayment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomaticPaymentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Title for this automatic payment (e.g., 'Booking Payment', 'Security Deposit')", max_length=255)),
                ('description_template', models.CharField(help_text='Description template - use {coliver_name}, {chapter_name}, {arrival_date}, {departure_date}', max_length=500)),
                ('date_type', models.CharField(choices=[('arrival_date', 'Arrival Date'), ('departure_date', 'Departure Date'), ('custom_offset', 'Custom Days After Arrival')], default='arrival_date', max_length=20)),
                ('days_offset', models.IntegerField(default=0, help_text='Days to add/subtract from the base date (negative for before, positive for after)')),
                ('amount_type', models.CharField(choices=[('fixed', 'Fixed Amount'), ('total_cost', 'Total Stay Cost'), ('percentage_cost', 'Percentage of Total Cost')], default='total_cost', max_length=20)),
                ('fixed_amount', models.DecimalField(blank=True, decimal_places=2, help_text="Fixed amount (only used if amount_type is 'fixed')", max_digits=10, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, help_text="Percentage of total cost (only used if amount_type is 'percentage_cost')", max_digits=5, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this template is active and should create payments')),
                ('applies_to_all_colivers', models.BooleanField(default=True, help_text='Whether this payment applies to all colivers')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payment_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AutomaticPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coliver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automatic_payments', to='colivers.coliver')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_automatic_payments', to=settings.AUTH_USER_MODEL)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='automatic_payment', to='payments.payment')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automatic_payments', to='payments.automaticpaymenttemplate')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('template', 'coliver')},
            },
        ),
    ]
