# Generated by Django 5.2 on 2025-05-26 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chapters', '0002_chapter_description_text_size'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterTransferRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('requested_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coliver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_transfer_requests', to=settings.AUTH_USER_MODEL)),
                ('current_chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_requests_from', to='chapters.chapter')),
                ('requested_chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_requests_to', to='chapters.chapter')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
