# Generated by Django 5.2 on 2025-05-26 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapter_transfers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chaptertransferrequest',
            name='requested_date',
        ),
        migrations.AddField(
            model_name='chaptertransferrequest',
            name='leave_date',
            field=models.DateField(help_text='When they want to leave their current chapter', null=True),
        ),
        migrations.AddField(
            model_name='chaptertransferrequest',
            name='start_date',
            field=models.DateField(help_text='When they want to start at the new chapter', null=True),
        ),
    ]
