# Generated by Django 5.2 on 2025-05-26 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chapter_transfers', '0002_remove_chaptertransferrequest_requested_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chaptertransferrequest',
            name='leave_date',
        ),
    ]
