# Generated by Django 5.2 on 2025-05-26 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapter_transfers', '0003_remove_chaptertransferrequest_leave_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferAcknowledgmentText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='I acknowledge that if there is currently another coliver residing in this chapter, I have communicated with them about switching rooms, and that they also have filled out this form')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Transfer Acknowledgment Text',
                'verbose_name_plural': 'Transfer Acknowledgment Text',
            },
        ),
        migrations.AddField(
            model_name='chaptertransferrequest',
            name='acknowledgment',
            field=models.BooleanField(default=False, help_text='User has acknowledged the transfer conditions'),
        ),
    ]
