# Generated by Django 5.2 on 2025-05-26 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapter_transfers', '0004_transferacknowledgmenttext_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaptertransferrequest',
            name='end_date',
            field=models.DateField(help_text='When they will end their stay at the current chapter', null=True),
        ),
    ]
