# Generated by Django 5.2 on 2025-05-25 15:14

from django.db import migrations, models

def set_default_is_active(apps, schema_editor):
    Application = apps.get_model('applications', 'Application')
    # Set is_active=True for all existing applications
    Application.objects.all().update(is_active=True)

def reverse_default_is_active(apps, schema_editor):
    pass  # No need to do anything when reversing

class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_application_manual_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_active',
            field=models.BooleanField(default=True, help_text='If unchecked, the application will be moved to the archive.'),
        ),
        migrations.RunPython(set_default_is_active, reverse_default_is_active),
    ]
