# Generated by Django 5.2 on 2025-05-25 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_application_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveApplication',
            fields=[
            ],
            options={
                'verbose_name': 'Active Application',
                'verbose_name_plural': 'Active Applications',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('applications.application',),
        ),
        migrations.CreateModel(
            name='ArchivedApplication',
            fields=[
            ],
            options={
                'verbose_name': 'Archived Application',
                'verbose_name_plural': 'Archived Applications',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('applications.application',),
        ),
    ]
