# Generated by Django 5.2 on 2025-05-25 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_activeapplication_archivedapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Unique identifier for this message', max_length=50, unique=True)),
                ('title', models.CharField(help_text='Title of the message', max_length=200)),
                ('content', models.TextField(help_text='Content of the message')),
                ('emoji', models.CharField(default='🌸', help_text='Emoji to display with the message', max_length=10)),
                ('button_text', models.CharField(default='I understand', help_text='Text to display on the acknowledgment button', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this message is currently active')),
            ],
            options={
                'verbose_name': 'Application Message',
                'verbose_name_plural': 'Application Messages',
            },
        ),
    ]
