# Generated by Django 5.2 on 2025-05-25 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_applicationmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortStayWarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Stay Duration Notice', max_length=200)),
                ('message', models.TextField(default='Please note that we prioritize stays over 1 month. While shorter stays are possible, longer-term residents will be given priority in the application process.')),
                ('button_text', models.CharField(default='I understand, continue anyway', max_length=50)),
                ('emoji', models.CharField(default='🌸', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Short Stay Warning Message',
                'verbose_name_plural': 'Short Stay Warning Message',
            },
        ),
    ]
