# Generated by Django 5.2 on 2025-05-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_shortstaywarning'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_discount', models.DecimalField(decimal_places=2, default=3.0, help_text='Percentage discount for returning members (e.g., 3.00 for 3%)', max_digits=5)),
                ('guest_increase', models.DecimalField(decimal_places=2, default=20.0, help_text='Percentage increase for second guest (e.g., 20.00 for 20%)', max_digits=5)),
                ('pricing_info_title', models.CharField(default='How Prices Are Calculated', max_length=200)),
                ('base_price_text', models.CharField(default='The nightly rate × number of nights', max_length=200)),
                ('member_discount_text', models.CharField(default='Returning members receive a {discount}% discount on the total price', max_length=200)),
                ('guest_increase_text', models.CharField(default='Selecting 2 guests adds a {increase}% increase to the total combined price for both guests', max_length=200)),
                ('calculation_note', models.TextField(default='Discounts and increases are calculated sequentially. For returning members with 2 guests, the {discount}% discount is applied first, followed by the {increase}% increase for the second guest.')),
            ],
            options={
                'verbose_name': 'Pricing Settings',
                'verbose_name_plural': 'Pricing Settings',
            },
        ),
        migrations.DeleteModel(
            name='ApplicationMessage',
        ),
        migrations.RemoveField(
            model_name='shortstaywarning',
            name='emoji',
        ),
    ]
