# Generated by Django 5.2 on 2025-05-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_pricingsettings_delete_applicationmessage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='application_status',
            field=models.CharField(choices=[('Approved for interview', 'Approved for interview'), ('Scheduled interview', 'Scheduled interview'), ('Interview passed', 'Interview passed'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted'), ('Waiting list', 'Waiting list'), ('Application in progress', 'Application in progress'), ('Submitted', 'Submitted'), ('Withdrawn', 'Withdrawn'), ('Onboarding', 'Onboarding')], default='Application in progress', max_length=40),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Withdrawn', 'Withdrawn')], default='Draft', max_length=20),
        ),
    ]
