# Generated by Django 5.2 on 2025-05-27 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_alter_application_application_status_and_more'),
        ('questions', '0002_reintroductionquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='reintroduction_completed',
            field=models.BooleanField(default=False, help_text='Whether the reintroduction form has been completed'),
        ),
        migrations.AddField(
            model_name='application',
            name='wants_reintroduction',
            field=models.BooleanField(blank=True, help_text='Whether the returning member wants to reintroduce themselves', null=True),
        ),
        migrations.CreateModel(
            name='ReintroductionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reintroduction_answers', to='applications.application')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='questions.reintroductionquestion')),
            ],
            options={
                'ordering': ['question__order'],
                'unique_together': {('application', 'question')},
            },
        ),
    ]
