# Generated by Django 5.2 on 2025-05-27 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0009_application_reintroduction_completed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReintroductionQuestionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Welcome Back!', max_length=200)),
                ('subtitle', models.CharField(default="We're excited to have you apply again.", max_length=200)),
                ('question_text', models.CharField(default='Would you like to reintroduce yourself?', max_length=300)),
                ('description', models.TextField(default='As a returning member, you have the option to share an updated introduction with the community. This is completely optional - you can choose to skip this step and submit your application directly.')),
                ('yes_option_title', models.CharField(default="Yes, I'd like to reintroduce myself", max_length=100)),
                ('yes_option_description', models.CharField(default='Complete the reintroduction form and submit your application', max_length=200)),
                ('no_option_title', models.CharField(default='No, skip the reintroduction', max_length=100)),
                ('no_option_description', models.CharField(default='Submit your application without reintroducing yourself', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Reintroduction Question Settings',
                'verbose_name_plural': 'Reintroduction Question Settings',
            },
        ),
    ]
