# Generated by Django 5.2 on 2025-05-27 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0010_reintroductionquestionsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortstaywarning',
            name='minimum_days',
            field=models.PositiveIntegerField(default=28, help_text='Minimum number of days before showing the short stay warning'),
        ),
    ]
