# Generated by Django 5.2 on 2025-05-27 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0011_shortstaywarning_minimum_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortstaywarning',
            name='long_stay_button_text',
            field=models.CharField(default='I understand, continue anyway', max_length=50),
        ),
        migrations.AddField(
            model_name='shortstaywarning',
            name='long_stay_message',
            field=models.TextField(default='Please note that initial bookings are limited to 3 months. You can extend your stay after arrival if space is available.'),
        ),
        migrations.AddField(
            model_name='shortstaywarning',
            name='long_stay_title',
            field=models.CharField(default='Extended Stay Notice', max_length=200),
        ),
        migrations.AddField(
            model_name='shortstaywarning',
            name='maximum_days',
            field=models.PositiveIntegerField(default=93, help_text='Maximum number of days before showing the long stay warning'),
        ),
    ]
