# Generated by Django 5.2 on 2025-05-25 12:19

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chapters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coliver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('arrival_date', models.DateField()),
                ('departure_date', models.DateField()),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('status', models.CharField(choices=[('ARCHIVE', 'Archive'), ('ONBOARDING', 'Onboarding'), ('COLIVING', 'Coliving'), ('APPLICATION', 'Application')], default='ONBOARDING', max_length=20)),
                ('chapter_name', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='colivers', to='chapters.chapter')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-arrival_date'],
            },
        ),
    ]
