# Generated by Django 5.2 on 2025-05-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colivers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coliver',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
