# Generated by Django 5.2 on 2025-05-25 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colivers', '0002_coliver_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coliver',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Manual override for the calculated cost', max_digits=10),
        ),
    ]
