# Generated by Django 5.2 on 2025-05-25 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colivers', '0003_alter_coliver_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coliver',
            name='cost',
        ),
        migrations.AddField(
            model_name='coliver',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
