# Generated by Django 5.2 on 2025-05-25 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colivers', '0004_remove_coliver_cost_coliver_total_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coliver',
            old_name='total_cost',
            new_name='cost',
        ),
    ]
