# Generated by Django 5.2 on 2025-05-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colivers', '0005_rename_total_cost_coliver_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coliver',
            name='cost',
        ),
        migrations.AddField(
            model_name='coliver',
            name='manual_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Override the automatically calculated cost. Leave empty to use calculated cost.', max_digits=10, null=True),
        ),
    ]
