# Generated by Django 5.2 on 2025-05-25 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colivers', '0006_remove_coliver_cost_coliver_manual_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveColiver',
            fields=[
            ],
            options={
                'verbose_name': 'Active Coliver',
                'verbose_name_plural': 'Active Colivers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('colivers.coliver',),
        ),
        migrations.CreateModel(
            name='ArchivedColiver',
            fields=[
            ],
            options={
                'verbose_name': 'Archived Coliver',
                'verbose_name_plural': 'Archived Colivers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('colivers.coliver',),
        ),
    ]
