# Generated by Django 5.2 on 2025-05-26 21:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colivers', '0008_coliver_is_active_alter_coliver_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coliver',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
