# Generated by Django 5.2 on 2025-05-25 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='description_text_size',
            field=models.CharField(choices=[('xs', 'Extra Small'), ('sm', 'Small'), ('base', 'Normal'), ('lg', 'Large'), ('xl', 'Extra Large')], default='sm', help_text='Choose the text size for the chapter description', max_length=10),
        ),
    ]
