# Generated by Django 5.2 on 2025-05-26 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0002_chapter_description_text_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='cost_per_night',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Cost per night in KRW', max_digits=10),
        ),
    ]
