# Generated by Django 5.2 on 2025-05-27 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0003_update_cost_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='use_tiered_pricing',
            field=models.BooleanField(default=False, help_text='Enable tiered pricing based on length of stay. If disabled, uses the legacy cost_per_night.'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='cost_per_night',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Legacy cost per night in KRW (used when no pricing tiers are defined)', max_digits=10),
        ),
        migrations.CreateModel(
            name='PricingTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier_name', models.CharField(help_text="Name for this pricing tier (e.g., 'Short-term', 'Mid-term', 'Long-term')", max_length=100)),
                ('duration_days', models.IntegerField(help_text='Number of days this tier covers (e.g., 84 for first 84 days)')),
                ('price_per_night', models.DecimalField(decimal_places=2, help_text='Price per night for this tier in KRW', max_digits=10)),
                ('tier_order', models.IntegerField(default=1, help_text='Order of this tier (1 = first tier, 2 = second tier, etc.)')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_tiers', to='chapters.chapter')),
            ],
            options={
                'ordering': ['chapter', 'tier_order'],
                'unique_together': {('chapter', 'tier_order')},
            },
        ),
    ]
