# Generated by Django 5.2 on 2025-05-27 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0004_chapter_use_tiered_pricing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='short_term_price_per_night',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Special price per night for short-term stays in KRW', max_digits=10),
        ),
        migrations.AddField(
            model_name='chapter',
            name='short_term_threshold_days',
            field=models.IntegerField(default=7, help_text='Maximum number of days to qualify for short-term pricing (e.g., 7 days)'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='use_short_term_pricing',
            field=models.BooleanField(default=False, help_text='Enable special pricing for very short stays (under the threshold).'),
        ),
    ]
