# Generated by Django 5.2 on 2025-05-25 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_remove_in_progress_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='assigned_to',
        ),
    ]
