# Generated by Django 5.2 on 2025-05-25 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_remove_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='coliver_name',
            field=models.CharField(blank=True, help_text='Name of the coliver associated with this task', max_length=255, null=True),
        ),
    ]
