# Generated by Django 5.2 on 2025-05-26 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_todo_coliver_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='coliver_name',
            field=models.CharField(blank=True, help_text='Name of the person associated with this task', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='task_type',
            field=models.CharField(choices=[('application_review', 'Application Review'), ('payment_review', 'Payment Review'), ('transfer_review', 'Transfer Review'), ('other', 'Other')], max_length=50),
        ),
    ]
