# Generated by Django 5.2 on 2025-05-27 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0006_alter_todo_task_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['-created_at'], 'verbose_name': 'Todo', 'verbose_name_plural': 'Todos'},
        ),
        migrations.RemoveField(
            model_name='todo',
            name='priority',
        ),
    ]
