# Generated by Django 5.2 on 2025-05-26 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_maintenancerequest_user_confirmation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceConfirmationText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='I confirm that this maintenance request is accurate and needs attention', help_text='This text will appear above the confirmation checkbox when users submit maintenance requests')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Maintenance Confirmation Text',
                'verbose_name_plural': 'Maintenance Confirmation Texts',
            },
        ),
    ]
