# Generated by Django 5.2 on 2025-05-26 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0005_completedmaintenancerequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='manager_checkbox',
        ),
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='manager_checkbox_label',
        ),
    ]
