# Generated by Django 5.2 on 2025-05-25 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('chapters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('date_join', models.DateField(blank=True, null=True, verbose_name='Arrival Date')),
                ('date_leave', models.DateField(blank=True, null=True, verbose_name='Departure Date')),
                ('member_type', models.CharField(choices=[('new member', 'new member'), ('returning member', 'returning member')], default='new member', max_length=20)),
                ('guests', models.CharField(choices=[('1', '1'), ('2', '2')], default='1', max_length=2)),
                ('application_status', models.CharField(choices=[('Approved for interview', 'Approved for interview'), ('Scheduled interview', 'Scheduled interview'), ('Interview passed', 'Interview passed'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted'), ('Waiting list', 'Waiting list'), ('Application in progress', 'Application in progress'), ('Submitted', 'Submitted'), ('Onboarding', 'Onboarding')], default='Application in progress', max_length=40)),
                ('application_answers', models.ManyToManyField(related_name='archive_application_answers', to='applications.applicationanswer')),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_applications', to='chapters.chapter')),
            ],
        ),
    ]
