# Generated by Django 5.2 on 2025-05-25 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='manual_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Override the automatically calculated cost. Leave empty to use calculated cost.', max_digits=10, null=True),
        ),
    ]
