# Generated by Django 5.2 on 2025-05-25 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Small square image (32x32 or 16x16 pixels) for the browser tab', null=True, upload_to='site_settings/'),
        ),
    ]
